### ISSUE TITLE
BUG - Keep previous versions of secrets

### ISSUE THREAD

**Issue by patpicos** [kevinhagenaars/SecureSecrets-VSTS#2]
Hi Kevin

Using your VSTS/Azure DevOps extension, I found a bug when using the "Keep Previous Secrets when exists"...the setting is not taking into effect and continues to generate a new value and creates a new version on KV. See below

![image](https://user-images.githubusercontent.com/25851869/46208164-dae5bd00-c2f7-11e8-9f79-f8263ff94070.png)

![image](https://user-images.githubusercontent.com/25851869/46208221-09fc2e80-c2f8-11e8-8df7-8de67c29f9db.png)

**Comment by kevinhagenaars** [comment]
I'll look into this!

**Comment by kevinhagenaars** [comment]
Could you give me some more information about the steps you did, as I can't reproduce the bug?

**Comment by patpicos** [comment]
unable to reproduce... closing

**Comment by patpicos** [comment]
I haven’t been able to reproduce! We can close
